services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_demo_db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: rag_demo
    ports:
      - "5433:5432" # Port diferit să nu conflicteze
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
